name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-macos-intel:
    name: Build macOS Intel
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build release binary
        run: cargo build --release

      - name: Create release archive
        run: |
          cp target/release/brewup .
          tar -czf brewup-x86_64-apple-darwin.tar.gz brewup

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: brewup-x86_64-apple-darwin
          path: brewup-x86_64-apple-darwin.tar.gz

  build-macos-arm:
    name: Build macOS ARM
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin

      - name: Build release binary
        run: cargo build --release --target aarch64-apple-darwin

      - name: Create release archive
        run: |
          cp target/aarch64-apple-darwin/release/brewup .
          tar -czf brewup-aarch64-apple-darwin.tar.gz brewup

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: brewup-aarch64-apple-darwin
          path: brewup-aarch64-apple-darwin.tar.gz

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Build release binary
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Create release archive
        run: |
          cp target/x86_64-unknown-linux-gnu/release/brewup .
          tar -czf brewup-x86_64-unknown-linux-gnu.tar.gz brewup

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: brewup-x86_64-unknown-linux-gnu
          path: brewup-x86_64-unknown-linux-gnu.tar.gz

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-macos-intel, build-macos-arm, build-linux]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List artifacts
        run: find artifacts -name "*.tar.gz" | sort

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*.tar.gz
