name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: brewup-x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: brewup-aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: brewup-x86_64-unknown-linux-gnu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}

    - name: Build release binary
      run: cargo build --release --target ${{ matrix.target }}

    - name: Strip binary (Unix)
      if: matrix.os != 'windows-latest'
      run: strip target/${{ matrix.target }}/release/brewup

    - name: Create release archive
      run: |
        mkdir -p dist
        cp target/${{ matrix.target }}/release/brewup dist/brewup
        tar -czf dist/${{ artifact_name }}.tar.gz -C dist brewup
        rm dist/brewup

    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ artifact_name }}
        path: dist/${{ artifact_name }}.tar.gz

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Display structure of downloaded files
      run: ls -R

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          brewup-x86_64-apple-darwin/brewup-x86_64-apple-darwin.tar.gz
          brewup-aarch64-apple-darwin/brewup-aarch64-apple-darwin.tar.gz
          brewup-x86_64-unknown-linux-gnu/brewup-x86_64-unknown-linux-gnu.tar.gz
